// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SinerjiOdev.Models;
using System;

namespace SinerjiOdev.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20171017122922_Caner")]
    partial class Caner
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SinerjiOdev.Models.Kullanıcı", b =>
                {
                    b.Property<int>("KullanıcıId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adi");

                    b.Property<string>("KullaniciAdi");

                    b.Property<string>("Sifre");

                    b.Property<string>("SoyAdi");

                    b.HasKey("KullanıcıId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SinerjiOdev.Models.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("KullanıcıId");

                    b.Property<string>("RolAd");

                    b.HasKey("RolID");

                    b.HasIndex("KullanıcıId");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("SinerjiOdev.Models.Rol", b =>
                {
                    b.HasOne("SinerjiOdev.Models.Kullanıcı", "Kullanıcı")
                        .WithMany("Roles")
                        .HasForeignKey("KullanıcıId")
                        .HasConstraintName("ForeignKey_Rol_Kullanıcı")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
